name = "GJRand"
uuid = "0c804728-dc53-409e-ba18-f4314f7fa6ff"
authors = ["snirgaz <snir.gazit@mail.huji.ac.il> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
